const products=window.KIM_PRODUCTS||[];
const grid=document.querySelector('#productGrid'),count=document.querySelector('#productCount'),heroCount=document.querySelector('#heroProductCount'),empty=document.querySelector('#emptyState'),searchInput=document.querySelector('#searchInput'),sortSelect=document.querySelector('#sortSelect'),bagDrawer=document.querySelector('#bagDrawer'),bagItems=document.querySelector('#bagItems'),bagCount=document.querySelector('#bagCount'),scrim=document.querySelector('#scrim');
let category='ALL',query='',sort='featured',bag=JSON.parse(localStorage.getItem('kim-bag-v4')||'[]');
const VER='20260913-v5'; const img=p=>`${p}?v=${VER}`; const eur=n=>new Intl.NumberFormat('en-FI',{style:'currency',currency:'EUR'}).format(n);
if(heroCount)heroCount.textContent=products.length;
function card(p){return `<article class="product-card glass" data-card="${p.id}"><a class="image-wrap" href="product.html?id=${encodeURIComponent(p.id)}" aria-label="View ${p.title}"><img src="${img(p.image)}" alt="${p.title}" loading="lazy"><span class="view-chip">View piece ↗</span></a><div class="product-info"><p class="category">${p.category}</p><h3 class="product-title"><a href="product.html?id=${encodeURIComponent(p.id)}">${p.title}</a></h3><span class="price">${eur(p.price)}</span><div class="card-actions"><button class="add-bag" data-add="${p.id}">Add to bag</button><button class="buy-now" data-buy="${p.id}" ${p.checkout?'':'disabled'}>${p.checkout?'Buy now ↗':'Coming soon'}</button></div></div></article>`}
function list(){let a=products.filter(p=>(category==='ALL'||p.category===category)&&(!query||`${p.title} ${p.category} ${p.description||''}`.toLowerCase().includes(query)));if(sort==='price-asc')a.sort((x,y)=>x.price-y.price);if(sort==='price-desc')a.sort((x,y)=>y.price-x.price);if(sort==='az')a.sort((x,y)=>x.title.localeCompare(y.title));if(sort==='featured')a.sort((x,y)=>x.featured-y.featured);return a}
function render(){const a=list();grid.innerHTML=a.map(card).join('');count.textContent=a.length;empty.hidden=!!a.length;requestAnimationFrame(()=>grid.querySelectorAll('.product-card').forEach((c,i)=>setTimeout(()=>c.classList.add('in'),i*28)))}
function save(){localStorage.setItem('kim-bag-v4',JSON.stringify(bag));renderBag()}
function add(id){if(!bag.includes(id))bag.push(id);save();openBag()}
function remove(id){bag=bag.filter(x=>x!==id);save()}
function renderBag(){bagCount.textContent=bag.length;if(!bag.length){bagItems.innerHTML='<p class="bag-empty">Your bag is empty.</p>';return}bagItems.innerHTML=bag.map(id=>{const p=products.find(x=>x.id===id);if(!p)return'';return `<div class="bag-item"><a href="product.html?id=${p.id}"><img src="${img(p.image)}" alt="${p.title}"></a><div><h3><a href="product.html?id=${p.id}">${p.title}</a></h3><p>${eur(p.price)}</p></div><div class="bag-item-actions"><button class="mini-buy" data-buy="${p.id}" ${p.checkout?'':'disabled'}>${p.checkout?'Checkout':'Soon'}</button><button class="remove" data-remove="${p.id}">Remove</button></div></div>`}).join('')}
function openBag(){bagDrawer.classList.add('open');bagDrawer.setAttribute('aria-hidden','false');scrim.hidden=false;document.body.style.overflow='hidden'}function closeBag(){bagDrawer.classList.remove('open');bagDrawer.setAttribute('aria-hidden','true');scrim.hidden=true;document.body.style.overflow=''}function buy(id){const p=products.find(x=>x.id===id);if(p?.checkout)location.href=p.checkout}
document.querySelectorAll('[data-category]').forEach(btn=>btn.addEventListener('click',()=>{category=btn.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===btn));render()}));searchInput.addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});sortSelect.addEventListener('change',e=>{sort=e.target.value;render()});document.querySelector('#headerSearch')?.addEventListener('click',()=>{searchInput.focus();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})});document.querySelector('#bagToggle')?.addEventListener('click',openBag);document.querySelector('#bagClose')?.addEventListener('click',closeBag);scrim?.addEventListener('click',closeBag);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBag()});document.addEventListener('click',e=>{const a=e.target.closest('[data-add]'),b=e.target.closest('[data-buy]'),r=e.target.closest('[data-remove]');if(a)add(a.dataset.add);if(b)buy(b.dataset.buy);if(r)remove(r.dataset.remove)});render();renderBag();
